INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (1, now(), 'ABCDEF12345', 'Muhammad Faisal', 'Hyder')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (2, now(), 'BCDEFG12345', 'John', 'Smith')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (3, now(), 'CDEFGH12345', 'John', 'Jones')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (4, now(), 'DEFGHI12345', 'Marcus', 'Rushford')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (5, now(), 'EFGHIJ12345', 'Lionel', 'Pepsi')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (6, now(), 'FGHIJK12345', 'Isco', 'Alarcon')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (7, now(), 'GHIJKL12345', 'Will', 'Smith')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (8, now(), 'HIJKLM12345', 'Christian', 'Bale')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (9, now(), 'IJKLMN12345', 'Bitch', 'Lasagna')
INSERT INTO EMPLOYEE(ID, CreatedDate, EmiratesID, FirstName, LastName) VALUES (10, now(), 'JKLMNO12345', 'Sergio', 'Ramos')