INSERT INTO ROLE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, Name) VALUES (-200, 'Muhammad Faisal Hyder', now(), '', null, 'ADMIN')
INSERT INTO ROLE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, Name) VALUES (-201, 'Muhammad Faisal Hyder', now(), '', null, 'USER')


INSERT INTO EMPLOYEE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, EmiratesID, FirstName, LastName, Email, StaffID, Password, ROLE_ID) VALUES (-11, 'Muhammad Faisal Hyder', now(), '', null, 'ABCDEFT12345', 'Muhammad Faisal', 'Hyder', 'faisal.haider@gmail.com', 'S779381', '$2a$10$qr.SAgYewyCOh6gFGutaWOQcCYMFqSSpbVZo.oqsc428xpwoliu7C', -200)
INSERT INTO EMPLOYEE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, EmiratesID, FirstName, LastName, Email, StaffID, Password, ROLE_ID) VALUES (-12, 'Muhammad Faisal Hyder', now(), '', null, 'BCDEFGT12345', 'John', 'Smith', 'john.Smith@gmail.com', 'S714781', '$2a$10$j9IjidIgwDfNGjNi8UhxAeLuoO8qgr/UH9W9.LmWJd/ohynhI7UJO', -201)
INSERT INTO EMPLOYEE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, EmiratesID, FirstName, LastName, Email, StaffID, Password, ROLE_ID) VALUES (-13, 'Muhammad Faisal Hyder', now(), '', null, 'CDEFGHT12345', 'John', 'Jones', 'john.Jones@ufc.com', 'S765678', '$2a$10$B558UyO3AH4CG9op8haUGu0h2fWIRfHYwlhUMjsl.7rlbBIJMmef2', -201)
INSERT INTO EMPLOYEE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, EmiratesID, FirstName, LastName, Email, StaffID, Password, ROLE_ID) VALUES (-14, 'Muhammad Faisal Hyder', now(), '', null, 'DEFGHIT12345', 'Marcus', 'Rushford', 'jushford@manu.com', 'S656671', '$2a$10$gpxFOzVCcvN3xKKEJmd5yuTpowmCn9wgFLuh619S0Equjdbb0Wf3C', -201)
INSERT INTO EMPLOYEE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, EmiratesID, FirstName, LastName, Email, StaffID, Password, ROLE_ID) VALUES (-15, 'Muhammad Faisal Hyder', now(), '', null, 'EFGHIJT12345', 'Lionel', 'Pepsi', 'jionel.Pepsi@barka.com', 'S777676', '$2a$10$Ka5iz/Nfq1/cFcuLRGaM5O3ImdaDdlcsDPq2I6wZR8UFAt4P6oG7e', -201)
INSERT INTO EMPLOYEE(ID, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, EmiratesID, FirstName, LastName, Email, StaffID, Password, ROLE_ID) VALUES (-16, 'Muhammad Faisal Hyder', now(), '', null, 'KLMNOPT12345', 'Muhammad Faisal', 'faisal.Islam@gmail.com', 'Islam', 'S754701', '$2a$10$pyznsDXWWWZQed6huQqHsu0RcbAEemoyiLv6cAgD1eQLeEpZvNiNW', -201)